<a href="https://colab.research.google.com/github/Sweta-Das/PyTorch-For-ML/blob/main/0_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.9.0+cu126'

### Scalar
A 0-dimension tensor, or simply a single number.

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

It means that although var 'scalar' is a single number, it's of type `torch.Tensor`.

In [3]:
# Dimension of tensor
scalar.ndim

0

In [4]:
# Retrieve the number from within the tensor
scalar.item()

7

### Vector
A single-dimension tensor, but can contain many numbers. It is a number with direction.

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
# Dimension
vector.ndim

1

In [7]:
# Shape of vector
vector.shape

torch.Size([2])

Shape tells how the elements inside the tensor is arranged.

### Matrix
A 2-dimensional array of numbers.

In [8]:
MATRIX = torch.tensor(
    [
        [7, 8],
        [9, 10]
    ]
)

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
# Dimension of matrix
MATRIX.ndim

2

In [10]:
# Shape of matrix
MATRIX.shape

torch.Size([2, 2])

### Tensor
An n-dimensional array of numbers.

In [11]:
TENSOR = torch.tensor(
    [
        [
          [1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]
        ]
    ]
)
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
# Dimension
TENSOR.ndim

3

In [13]:
# Shape
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

A ML model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it...

1. Start with random numbers
2. Look at data
3. Update random numbers
4. Look at data
5. Update random numbers ...

In [14]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(
    size = (3, 4)
)
random_tensor

tensor([[0.9334, 0.5624, 0.8952, 0.6577],
        [0.5981, 0.7743, 0.6749, 0.1403],
        [0.3307, 0.2905, 0.7162, 0.2411]])

In [15]:
random_tensor.dtype

torch.float32

In [16]:
# Create a random tensor in the common image shape ([height, width, color_channels])
random_img_size_tensor = torch.rand(size=(224, 224, 3))
random_img_size_tensor.shape

torch.Size([224, 224, 3])

In [17]:
random_img_size_tensor.ndim

3

## Zeros & Ones

Mostly used for masking where some of the values in one tensors is converted to zeros to let a model know not to learn them.

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros.dtype

torch.float32

In [20]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

## Range in tensors
1 to 10 or, 0 to 100.

In [22]:
# Create a range of values from 0 to 10
zero_to_ten = torch.arange(
    start=0,
    end=10,
    step=1
)

zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Tensor with the same shape as another

In [23]:
# Create a zeros tensor similar to another tensor
zeros_tnsr = torch.zeros_like(
    input = zero_to_ten
)
zeros_tnsr

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

A tensor filled with zeros with the same shape as previous input (zero_to_ten).

In [24]:
# Create a ones tensor similar to another tensor
ones_tnsr = torch.ones_like(
    input = zero_to_ten
)
ones_tnsr

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Tensor Datatypes

There are many different types of tensor datatypes available in PyTorch. Some are specific for CPU and some are better for GPU.

- `torch.cuda` -> Tensor is being used for GPU (since Nvidia GPUs use computing toolkit called CUDA)

- Default type : **32-bit floating point** -> `torch.float32` or `torch.float`

- **16-bit floating point** -> `torch.float16` or `torch.half`

- **64-bit floating point** -> `torch.float64` or `torch.double`

There's also 8-bit, 16-bit, 32-bit and 64-bit integers, plus more!

## Reason for Datatypes : Precision

- Precision is the amount of detail used to describe a number.
- Higher the precision value, the more detail and hence data used to express a number.
- The more detail you've to calculate, the more compute you've to use. </br>
So, lower precision datatypes are generally faster, but fall behind in evaluation metrics like accuracy.
</br>

Resources:
- https://docs.pytorch.org/docs/stable/tensors.html#data-types
- https://en.wikipedia.org/wiki/Precision_(computer_science)


In [28]:
# Create tensors with default datatype
float32_tnsr = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype = None, # defaults to None so, torch.float32 get selected
    device = None, # defaults to None, which uses the default tensor type
    requires_grad = False # if True, operations performed on tensor are recorded
)
float32_tnsr.shape

torch.Size([3])

In [29]:
float32_tnsr.dtype, float32_tnsr.device

(torch.float32, device(type='cpu'))

Most common issues while using PyTorch are:
- shape issues (tensor shapes don't match up),
- datatype, and
- device issues.
</br>

PyTorch often likes tensors to be of the same format, if one of the tensor is of `dtype = torch.float32`, and the other is `dtype = torch.float16`, it'll throw error.
</br>

Also, if one of the tensor is on CPU and another on the GPU, then there'll be error, because PyTorch likes calculations between tensors to be on the same device.

In [30]:
float16_tnsr = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=torch.float16
)
float16_tnsr.dtype

torch.float16

# Getting information from tensors

3 most common attributes to find out about tensors:
- shape -> what shape is the tensor?
  - Some operations require specific shape rules.
- dtype -> what datatype are the elements within the tensor stored in?
- device -> what device is the tensor stored on? (GPU/CPU)

In [31]:
# Create a random tensor and find out its details
tnsr = torch.rand(size=(3, 4))
print(tnsr)
print(f"Shape of tensor: {tnsr.shape}")
print(f"Datatype of tensor: {tnsr.dtype}")
print(f"Device tensor is stored on: {tnsr.device}")

tensor([[0.9329, 0.1191, 0.7536, 0.6365],
        [0.6241, 0.7841, 0.1457, 0.2920],
        [0.9384, 0.2035, 0.5180, 0.3741]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


***Note**: When you run into issues in PyTorch, it's very often one to do with one of the three attributes above. So when the error messages show up, sing yourself a little song called "what, what, where":*

- what shape are my tensors?
- what datatype are they and
- where are they stored? </br>

"what shape, what datatype, where where where"

# Manipulating Tensors (Tensor Ops)