<a href="https://colab.research.google.com/github/Sweta-Das/PyTorch-For-ML/blob/main/Fundamentals/0_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.9.0+cpu'

### Scalar
A 0-dimension tensor, or simply a single number.

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

It means that although var 'scalar' is a single number, it's of type `torch.Tensor`.

In [3]:
# Dimension of tensor
scalar.ndim

0

In [4]:
# Retrieve the number from within the tensor
scalar.item()

7

### Vector
A single-dimension tensor, but can contain many numbers. It is a number with direction.

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
# Dimension
vector.ndim

1

In [7]:
# Shape of vector
vector.shape

torch.Size([2])

Shape tells how the elements inside the tensor is arranged.

### Matrix
A 2-dimensional array of numbers.

In [8]:
MATRIX = torch.tensor(
    [
        [7, 8],
        [9, 10]
    ]
)

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
# Dimension of matrix
MATRIX.ndim

2

In [10]:
# Shape of matrix
MATRIX.shape

torch.Size([2, 2])

### Tensor
An n-dimensional array of numbers.

In [11]:
TENSOR = torch.tensor(
    [
        [
          [1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]
        ]
    ]
)
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
# Dimension
TENSOR.ndim

3

In [13]:
# Shape
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

A ML model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it...

1. Start with random numbers
2. Look at data
3. Update random numbers
4. Look at data
5. Update random numbers ...

In [14]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(
    size = (3, 4)
)
random_tensor

tensor([[0.4692, 0.6307, 0.1515, 0.5194],
        [0.7809, 0.6785, 0.3673, 0.8966],
        [0.6674, 0.0448, 0.7395, 0.5252]])

In [15]:
random_tensor.dtype

torch.float32

In [16]:
# Create a random tensor in the common image shape ([height, width, color_channels])
random_img_size_tensor = torch.rand(size=(224, 224, 3))
random_img_size_tensor.shape

torch.Size([224, 224, 3])

In [17]:
random_img_size_tensor.ndim

3

## Zeros & Ones

Mostly used for masking where some of the values in one tensors is converted to zeros to let a model know not to learn them.

In [18]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros.dtype

torch.float32

In [20]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

## Range in tensors
1 to 10 or, 0 to 100.

In [22]:
# Create a range of values from 0 to 10
zero_to_ten = torch.arange(
    start=0,
    end=10,
    step=1
)

zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Tensor with the same shape as another

In [23]:
# Create a zeros tensor similar to another tensor
zeros_tnsr = torch.zeros_like(
    input = zero_to_ten
)
zeros_tnsr

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

A tensor filled with zeros with the same shape as previous input (zero_to_ten).

In [24]:
# Create a ones tensor similar to another tensor
ones_tnsr = torch.ones_like(
    input = zero_to_ten
)
ones_tnsr

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Tensor Datatypes

There are many different types of tensor datatypes available in PyTorch. Some are specific for CPU and some are better for GPU.

- `torch.cuda` -> Tensor is being used for GPU (since Nvidia GPUs use computing toolkit called CUDA)

- Default type : **32-bit floating point** -> `torch.float32` or `torch.float`

- **16-bit floating point** -> `torch.float16` or `torch.half`

- **64-bit floating point** -> `torch.float64` or `torch.double`

There's also 8-bit, 16-bit, 32-bit and 64-bit integers, plus more!

## Reason for Datatypes : Precision

- Precision is the amount of detail used to describe a number.
- Higher the precision value, the more detail and hence data used to express a number.
- The more detail you've to calculate, the more compute you've to use. </br>
So, lower precision datatypes are generally faster, but fall behind in evaluation metrics like accuracy.
</br>

Resources:
- https://docs.pytorch.org/docs/stable/tensors.html#data-types
- https://en.wikipedia.org/wiki/Precision_(computer_science)


In [25]:
# Create tensors with default datatype
float32_tnsr = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype = None, # defaults to None so, torch.float32 get selected
    device = None, # defaults to None, which uses the default tensor type
    requires_grad = False # if True, operations performed on tensor are recorded
)
float32_tnsr.shape

torch.Size([3])

In [26]:
float32_tnsr.dtype, float32_tnsr.device

(torch.float32, device(type='cpu'))

Most common issues while using PyTorch are:
- shape issues (tensor shapes don't match up),
- datatype, and
- device issues.
</br>

PyTorch often likes tensors to be of the same format, if one of the tensor is of `dtype = torch.float32`, and the other is `dtype = torch.float16`, it'll throw error.
</br>

Also, if one of the tensor is on CPU and another on the GPU, then there'll be error, because PyTorch likes calculations between tensors to be on the same device.

In [27]:
float16_tnsr = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=torch.float16
)
float16_tnsr.dtype

torch.float16

# Getting information from tensors

3 most common attributes to find out about tensors:
- shape -> what shape is the tensor?
  - Some operations require specific shape rules.
- dtype -> what datatype are the elements within the tensor stored in?
- device -> what device is the tensor stored on? (GPU/CPU)

In [28]:
# Create a random tensor and find out its details
tnsr = torch.rand(size=(3, 4))
print(tnsr)
print(f"Shape of tensor: {tnsr.shape}")
print(f"Datatype of tensor: {tnsr.dtype}")
print(f"Device tensor is stored on: {tnsr.device}")

tensor([[0.1133, 0.2434, 0.4115, 0.7898],
        [0.4835, 0.3202, 0.6544, 0.9802],
        [0.5095, 0.3791, 0.3179, 0.4448]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


***Note**: When you run into issues in PyTorch, it's very often one to do with one of the three attributes above. So when the error messages show up, sing yourself a little song called "what, what, where":*

- what shape are my tensors?
- what datatype are they and
- where are they stored? </br>

"what shape, what datatype, where where where"

# Manipulating Tensors (Tensor Ops)

### Basic Operations:
- Addition (+)
- Subtraction (-)
- Multiplicaiton (*)
- Division (/)

In [29]:
# Create a tensor & add number to it
tnsr = torch.tensor([1, 2, 3])
tnsr + 10

tensor([11, 12, 13])

In [30]:
# Multiply tensor by 10
tnsr * 10

tensor([10, 20, 30])

In [31]:
tnsr

tensor([1, 2, 3])

Tensor values inside the tensor don't change unless they're reassigned.

In [32]:
# Subtract and reassign
tnsr = tnsr - 10
tnsr

tensor([-9, -8, -7])

In [33]:
# Add & reassign
tnsr = tnsr + 10
tnsr

tensor([1, 2, 3])

In [34]:
# PyTorch Built-in functions
torch.multiply(tnsr, 10)

tensor([10, 20, 30])

In [35]:
torch.add(tnsr, 10)

tensor([11, 12, 13])

In [36]:
tnsr

tensor([1, 2, 3])

Original tensor is still unchanged.

In [37]:
# Element-wise multiplication
print(tnsr, '*', tnsr)
print('Equals:', tnsr * tnsr)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


## Matrix Multiplication

2 rules for matrix multiplication in PyTorch are:
- Inner dimensions must match.
- Resulting matrix has the shape of the outer dimensions.

In [38]:
tnsr

tensor([1, 2, 3])

In [39]:
tnsr.shape

torch.Size([3])

Difference between element-wise multiplication and matrix multiplication is the addition of values.

In [40]:
# Element-wise matrix multiplication
tnsr * tnsr

tensor([1, 4, 9])

In [41]:
# Matrix multiplication
torch.matmul(tnsr, tnsr)

tensor(14)

In [42]:
tnsr @ tnsr

tensor(14)

In Python, matrix multiplication can performed using `@` symbol.

In [43]:
# Matrix multiplication by hand
%%time
value = 0
for i in range(len(tnsr)):
  value += tnsr[i] * tnsr[i]
value

CPU times: user 1.8 ms, sys: 262 µs, total: 2.06 ms
Wall time: 3.02 ms


tensor(14)

In [44]:
%%time
torch.matmul(tnsr, tnsr)

CPU times: user 63 µs, sys: 10 µs, total: 73 µs
Wall time: 76.3 µs


tensor(14)

# Most common errors in Deep Learning

## Shape Errors

Shape mismatch is the most common error while performing operations on matrices.

In [45]:
tnsr_A = torch.tensor(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ],
    dtype=torch.float32
)

tnsr_B = torch.tensor(
    [
        [7, 10],
        [8, 11],
        [9, 12]
    ],
    dtype = torch.float32
)

In [46]:
tnsr_A.shape, tnsr_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [47]:
torch.matmul(tnsr_A, tnsr_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To multiplt mismatched shapes tensors, we need to perform matrix transpose.

In [48]:
tnsr_A, tnsr_B

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 tensor([[ 7., 10.],
         [ 8., 11.],
         [ 9., 12.]]))

In [49]:
tnsr_B.T

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

In [50]:
print(f"New shapes: tensor_A = {tnsr_A.shape} (same as above), \
tensor_B = {tnsr_B.T.shape}\n")
print(f"Multiplying: {tnsr_A.shape} * {tnsr_B.T.shape} <- inner dimension \
match\n")
print("Output: \n")
output = torch.matmul(tnsr_A, tnsr_B.T)
print(output)
print(f"\n Output shape: {output.shape}")

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimension match

Output: 

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

 Output shape: torch.Size([3, 3])


In [51]:
# torch.mm <- Shortcut for matmul
torch.mm(tnsr_A, tnsr_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

***Note**: Such matrix multiplication is also referred to as the **dot product** of 2 matrices.*

`torch.nn.Linear()` </br>

- Given module is also known as **Feed-Forward Layer** or **Fully Connected Layer**
- This module implements a matrix multiplication between an input `x` and a weights matrix `A`.

$$y=x\cdot{W^T} + b$$
  
    - `x` is input to the layer
    - `W` is weight matrix created by the layer. This starts out as random numbers that get adjusted as a neural network learns to better represent data patterns.
    - `b` is bias term used to slightly offset the weights and inputs
    - `y` is output

This is a linear function that is used to draw a straight line.

In [52]:
# Starting linear layers with random weights matrix
torch.manual_seed(42) # for reproducibility
linear = torch.nn.Linear(
    in_features=2, # matches inner dimension of input
    out_features=6 # describes outer value
)

x = tnsr_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output: \n{output}\n Output shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output: 
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)
 Output shape: torch.Size([3, 6])


In [53]:
# Changing `in_features` from 2 to 3
linear = torch.nn.Linear(
    in_features=3, # matches inner dimension of input
    out_features=6 # describes outer value
)

x = tnsr_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output: \n{output}\n Output shape: {output.shape}")

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x6)

In [54]:
linear = torch.nn.Linear(
    in_features=3, # matches inner dimension of input
    out_features=6 # describes outer value
)

x = tnsr_A
output = linear(x.T)
print(f"Input shape: {x.T.shape}\n")
print(f"Output: \n{output}\n Output shape: {output.shape}")

Input shape: torch.Size([2, 3])

Output: 
tensor([[ 3.4945,  0.8699, -3.4421,  0.6183,  1.9736, -0.8259],
        [ 4.5867,  1.0541, -4.0723,  0.4261,  2.5616, -0.7943]],
       grad_fn=<AddmmBackward0>)
 Output shape: torch.Size([2, 6])


***Note: Matrix Multiplications is all you need.***
https://marksaroufim.substack.com/p/working-class-deep-learner

## Aggregation of Tensor
Finding min, max, mean, sum, etc.

In [55]:
x = torch.arange(
    start=0,
    end=100,
    step=10
)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [56]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
print(f"Mean: {x.type(torch.float32).mean()}")
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


***Note**: Methods such as `torch.mean()` require tensors to be in `torch.float32` or another specific datatype, otherwise the operation fails.*

In [57]:
# Using torch methods
print(f"Minimum: {torch.max(x)}")
print(f"Maximum: {torch.min(x)}")
print(f"Mean: {torch.mean(x.type(torch.float32))}")
print(f"Sum: {torch.sum(x)}")

Minimum: 90
Maximum: 0
Mean: 45.0
Sum: 450


## Positional min/max
Finding the index of a tensor where the max or min occurs

In [58]:
tnsr = torch.arange(
    start=10,
    end=100,
    step=10
)
print(f"Tensor: {tnsr}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])


In [59]:
print(f"Index with max value: {tnsr.argmax()}")
print(f"Index with min value: {tnsr.argmin()}")

Index with max value: 8
Index with min value: 0


## Change tensor datatype


In [60]:
# Create a tensor and check its datatype
tnsr = torch.arange(10., 100., 10.)
tnsr.dtype

torch.float32

In [66]:
tnsr_flt16 = tnsr.type(torch.float16)
tnsr_flt16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [67]:
tnsr_int8 = tnsr.type(torch.int8)
tnsr_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

***Note**: Lower the number (e.g., 32, 16, 8), the less precise a computer stores the value.*
- With a lower amount of storage, lower number results in faster computation and a smaller overall model.
- Mobile-based neural networks often operate with 8-bit integers, smaller and faster to run but less accurate than their float32 counterparts.

## Reshaping, stacking, squeezing and unsqueezing

In [68]:
# Create a tensor
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [69]:
# Add an extra dim
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [70]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

https://stackoverflow.com/a/54507446/7900723

***Note:** Changing the view of a tensor with `torch.view()` really only creates a new view of the same tensor.*

In [71]:
# Changing the view changes the original tensor too
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [72]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [73]:
# Changing dim of stacked tensors
x_stacked_dim = torch.stack([x, x, x, x], dim=1)
x_stacked_dim

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [74]:
# Removing all single dimensions from a tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous tensor shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New tensor shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous tensor shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New tensor shape: torch.Size([7])


In [75]:
# Reversing the squeeze
print(f"Previous tensor: {x_squeezed}")
print(f"Previous tensor shape: {x_squeezed.shape}")

# Adding an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New tensor shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous tensor shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New tensor shape: torch.Size([1, 7])


In [76]:
# Rearrange the order of axes values; `input` -> `view` with new dims

# Create a tensor with specific shape
x_org = torch.rand(size = (224, 224, 3))
# Permute the original tensor to rearrange the axis order
x_permuted = x_org.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_org.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


***Note**: Since permuting returns a view (i.e. shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and by changing the values in the view, it will change the values of the original.*

# Indexing (selecting data from tensors)



In [78]:
# Create a new tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

Indexing values goes outer dimension -> inner dimension

In [79]:
# Index bracket by bracket
print(f"1st square bracket: \n{x[0]}")
print(f"2nd square bracket: \n{x[0][0]}")
print(f"3rd square bracket: \n{x[0][0][0]}")

1st square bracket: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
2nd square bracket: 
tensor([1, 2, 3])
3rd square bracket: 
1


We can also use `:` to specify "all values in this dimension" and then use a comma (,) to add another dimension.

In [80]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [81]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [82]:
# Get all values of 0th dimension buy only 1 index value of the 1st  & 2nd dimension
x[:, 1, 1]

tensor([5])

In [83]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

# PyTorch tensors & NumPy

2 main methods for NumPy to PyTorch & back are:
- `torch.from_numpy(ndarray)`
- `torch.Tensor.numpy()`

In [84]:
# NumPy array to tensor
import numpy as np

arr = np.arange(1.0, 8.0)
tnsr = torch.from_numpy(arr)
arr, tnsr

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

***Note**: By default, NumPy arrays are created with the datatype `float64`. Converting it to a PyTorch tensor, maintains the same datatype.*

In [85]:
# Change the array, keep the tensor
arr = arr + 1
arr, tnsr

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [86]:
# Tensor to NumPy array
tnsr = torch.ones(7)
numpy_tnsr = tnsr.numpy()
tnsr, numpy_tnsr

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

By default, tensors are created with the datatype `float32`. Converting it to a NumPy array, maintains the same datatype as well.

In [87]:
# Change the tensor, keep the array
tnsr = tnsr + 1
tnsr, numpy_tnsr

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility


Pseudorandomness plays an important role in neural networks and machine learning. A computer is fundamentally deterministic (each step is predictable), so the randomness present are basically a simulated randomness.

- To better describe data patterns:
  - Start with random numbers -> tensor operations -> try to make better (again & again & again)

- However to perform repeatable experiments, we require reproducibility.
  - It's the way to get the same (or very similar) results on computer running the same code.

In [88]:
# Create 2 random tensors
rand_tnsr_A = torch.rand(3, 4)
rand_tnsr_B = torch.rand(3, 4)

print(f"Tensor A: \n{rand_tnsr_A}\n")
print(f"Tensor B: \n{rand_tnsr_B}\n")

print(f"Does Tensor A equal Tensor B? (anywhere)")
rand_tnsr_A == rand_tnsr_B

Tensor A: 
tensor([[0.8973, 0.3629, 0.1748, 0.2401],
        [0.5457, 0.7303, 0.5268, 0.6694],
        [0.3213, 0.4008, 0.2892, 0.9977]])

Tensor B: 
tensor([[0.6649, 0.5646, 0.9323, 0.4621],
        [0.4027, 0.1680, 0.1170, 0.5063],
        [0.6061, 0.5141, 0.1907, 0.0445]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Here, tensors come out with different values. </br>

What if we want to contain random values but of the same flavour?

In [89]:
# Create flavoured random tensors
import random

RANDOM_SEED = 42
torch.manual_seed(seed = RANDOM_SEED)
rand_tnsr_C = torch.rand(3, 4)

torch.random.manual_seed(seed = RANDOM_SEED)
rand_tnsr_D = torch.rand(3, 4)

print(f"Tensor C: \n{rand_tnsr_C}\n")
print(f"Tensor D: \n{rand_tnsr_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
rand_tnsr_C == rand_tnsr_D

Tensor C: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [90]:
# Changing the random seed
import random

RANDOM_SEED = 2
torch.manual_seed(seed = RANDOM_SEED)
rand_tnsr_C = torch.rand(3, 4)

torch.random.manual_seed(seed = RANDOM_SEED)
rand_tnsr_D = torch.rand(3, 4)

print(f"Tensor C: \n{rand_tnsr_C}\n")
print(f"Tensor D: \n{rand_tnsr_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
rand_tnsr_C == rand_tnsr_D

Tensor C: 
tensor([[0.6147, 0.3810, 0.6371, 0.4745],
        [0.7136, 0.6190, 0.4425, 0.0958],
        [0.6142, 0.0573, 0.5657, 0.5332]])

Tensor D: 
tensor([[0.6147, 0.3810, 0.6371, 0.4745],
        [0.7136, 0.6190, 0.4425, 0.0958],
        [0.6142, 0.0573, 0.5657, 0.5332]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [91]:
# Commenting out the manual seed in tensor D
import random

RANDOM_SEED = 42
torch.manual_seed(seed = RANDOM_SEED)
rand_tnsr_C = torch.rand(3, 4)

# torch.random.manual_seed(seed = RANDOM_SEED)
rand_tnsr_D = torch.rand(3, 4)

print(f"Tensor C: \n{rand_tnsr_C}\n")
print(f"Tensor D: \n{rand_tnsr_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
rand_tnsr_C == rand_tnsr_D

Tensor C: 
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D: 
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Without equal `RANDOM_SEED`, tensors are different, and can't be reproducible.

References:
- https://docs.pytorch.org/docs/stable/notes/randomness.html
- https://en.wikipedia.org/wiki/Random_seed

# Running Tensors on GPUs